# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-28 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender1',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
