# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190828_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender1',
            name='a',
            field=models.DateField(auto_now=True),
        ),
    ]
