# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-28 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gender1_a'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gender1',
            new_name='gender2',
        ),
    ]
