# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-28 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190828_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gender2',
            new_name='gender1',
        ),
    ]
