# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-30 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190830_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender2',
            name='a',
        ),
        migrations.RemoveField(
            model_name='gender2',
            name='created',
        ),
    ]
