# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191008_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tweet',
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='users.tweet9'),
            preserve_default=False,
        ),
    ]
