# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet9file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('tweet9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.tweet9')),
            ],
        ),
    ]
