# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-22 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bussiness2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(default='default.jpg', upload_to='media')),
                ('street', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bussiness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bussiness3',
            name='user',
        ),
        migrations.DeleteModel(
            name='bussiness3',
        ),
    ]
