# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0003_auto_20190824_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness2',
            name='pincode',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
