# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0005_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='user_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
