# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-30 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20190828_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('professtion', models.CharField(max_length=160)),
                ('a', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gender1',
            name='user',
        ),
        migrations.DeleteModel(
            name='gender1',
        ),
    ]
