# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190830_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
