# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-04 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='address1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
