# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191008_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pincode',
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ManyToManyField(related_name='tweet', to='users.tweet9'),
        ),
    ]
