# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-15 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tweet9file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet9',
            name='file',
        ),
    ]
