# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190913_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comments'),
        ),
    ]
